# Generated by Django 4.2 on 2023-05-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='type_diplome',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.AddField(
            model_name='diplome',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorie'),
        ),
    ]
