# Generated by Django 4.2 on 2023-05-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_diplome_alter_categorie_type_diplome_delete_matiere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='diplome',
            name='option',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
