# Generated by Django 4.2 on 2023-05-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_options_diplome_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.options'),
        ),
    ]
