# Generated by Django 4.2 on 2023-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='stars',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
