# Generated by Django 4.2 on 2023-05-12 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='diplome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.diplome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='montant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
